FROM golang:1.22.0

WORKDIR /app

ARG ARG_NOIP_HOSTNAME
ARG ARG_CLOUDFLARE_EMAIL        
ARG ARG_CLOUDFLARE_API_KEY      
ARG ARG_CLOUDFLARE_A_RECORD_NAME
ARG ARG_CLOUDFLARE_ZONE_ID 
ARG ARG_DISCORD_WEBHOOK

ENV NOIP_HOSTNAME=${ARG_NOIP_HOSTNAME:-noip-hostname}
ENV CLOUDFLARE_EMAIL=${ARG_CLOUDFLARE_EMAIL:-cloudflare-email}
ENV CLOUDFLARE_API_KEY=${ARG_CLOUDFLARE_API_KEY:-cloudflare-api-key}
ENV CLOUDFLARE_A_RECORD_NAME=${ARG_CLOUDFLARE_A_RECORD_NAME:-cloudflare-a-record-name}
ENV CLOUDFLARE_ZONE_ID=${ARG_CLOUDFLARE_ZONE_ID:-cloudflare-zone-id}
ENV DISCORD_WEBHOOK=${ARG_DISCORD_WEBHOOK:-discord-webhook}

COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -v -o ddns

CMD ["./ddns"]